### ISSUE TITLE
Google Analytics Tracking

### ISSUE THREAD

**Issue by Zelig880** [smartcontractkit/blockchain-ecosystem-map#37]
Implement Google Analytics Tracking using "https://www.npmjs.com/package/react-gtm-module"

- [x] Add module
- [x] Add a component that loads the Tracking
- [x] Create an environment variable for the tracking (call it NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING)
- [x] Create an environment.example file with the above environment variable
